"""
API Key Domain Model

Defines API Key related Data Transfer Objects (DTOs).
"""

import re
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class ApiKeyBase(BaseModel):
    """API Key Base Model"""

    # Key Name
    key_name: str = Field(..., min_length=1, max_length=100, description="Key Name")

    @field_validator("key_name")
    @classmethod
    def validate_key_name(cls, v: str) -> str:
        """Validate key_name to prevent injection attacks"""
        # Trim whitespace
        v = v.strip()
        if not v:
            raise ValueError("key_name cannot be empty or whitespace only")
        # Check for potentially dangerous characters
        # Allow alphanumeric, underscores, hyphens, spaces, and common CJK characters
        if not re.match(r"^[\w\s\-\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]+$", v):
            raise ValueError(
                "key_name can only contain letters, numbers, underscores, hyphens, spaces, and CJK characters"
            )
        return v


class ApiKeyCreate(ApiKeyBase):
    """Create API Key Request Model"""

    # key_value is automatically generated by the backend, no need for client to provide
    record_details: bool = Field(
        True, description="Whether to record request detail payload (bodies & headers)"
    )


class ApiKeyUpdate(BaseModel):
    """Update API Key Request Model"""

    key_name: Optional[str] = Field(None, min_length=1, max_length=100)
    is_active: Optional[bool] = None
    record_details: Optional[bool] = Field(
        None, description="Whether to record request detail payload (bodies & headers)"
    )


class ApiKeyModel(ApiKeyBase):
    """API Key Complete Model"""

    id: int = Field(..., description="API Key ID")
    key_value: str = Field(..., description="Key Value")
    is_active: bool = Field(True, description="Is Active")
    record_details: bool = Field(
        True, description="Whether to record request detail payload (bodies & headers)"
    )
    created_at: datetime = Field(..., description="Creation Time")
    last_used_at: Optional[datetime] = Field(None, description="Last Used Time")

    model_config = ConfigDict(from_attributes=True)


class ApiKeyResponse(ApiKeyBase):
    """API Key Response Model (key_value sanitized)"""

    id: int = Field(..., description="API Key ID")
    # key_value sanitized display
    key_value: str = Field(..., description="Key Value (Sanitized)")
    is_active: bool = Field(True, description="Is Active")
    record_details: bool = Field(
        True, description="Whether to record request detail payload (bodies & headers)"
    )
    created_at: datetime = Field(..., description="Creation Time")
    last_used_at: Optional[datetime] = Field(None, description="Last Used Time")
    # Current month's total cost (USD)
    monthly_cost: Optional[float] = Field(None, description="Current month's total cost (USD)")

    model_config = ConfigDict(from_attributes=True)


class ApiKeyCreateResponse(ApiKeyBase):
    """Create API Key Response Model (key_value fully displayed, once only)"""

    id: int = Field(..., description="API Key ID")
    # Return full key_value on creation, not displayed afterwards
    key_value: str = Field(..., description="Key Value (Fully displayed only on creation)")
    is_active: bool = Field(True, description="Is Active")
    record_details: bool = Field(
        True, description="Whether to record request detail payload (bodies & headers)"
    )
    created_at: datetime = Field(..., description="Creation Time")
    last_used_at: Optional[datetime] = Field(None, description="Last Used Time")

    model_config = ConfigDict(from_attributes=True)
